name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: run-tests
    steps:
      - name: Clone Source Code
        uses: actions/checkout@v4
      - name: install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
  deploy:
    runs-on: ubuntu-latest
    name: start-deploy
    needs: test
    steps:
      - name: Connect with EC2 using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd Workshop
            git pull origin main
  notify:
      needs: test
      if: failure()
      runs-on: ubuntu-latest
      steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Test job failed in ${{github.repository}}
          body: The test job in the CI/CD pipeline for ${{github.repository}} failed or did not complete
          to: jomanfail159@gmail.com
          from: GitHub Actions