name: CI-CD

on:
  push:
    branches:
      - main

runs-on: ubuntu-latest

jobs:
  test:
    steps:
      - name: Clone Source Code
      - uses: actions/checkout@v4
      - name: install Nodejs
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Project Packages
        run: npm ci
      - name: running tests
        run: npm test