name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: run-tests
    steps:
      - name: Clone Source Code
        uses: actions/checkout@v4
      - name: install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
